"""
Django settings for djT project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+x=6@jabz=it(xocf^7+m&r_y=0nig*tvz_dl2mx*rw0xsj5ud'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# 'app_name.Model'  自定义模型 代替 原有的 User
AUTH_USER_MODEL = 'account.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.news.apps.NewsConfig',
    'apps.course.apps.CourseConfig',
    'apps.doc.apps.DocConfig',
    'apps.account.apps.AccountConfig',
    'apps.admin',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # {%load static%}  href src {% static '/static/'%}
            'builtins': ['django.templatetags.static'],
        },
    },
]

WSGI_APPLICATION = 'dj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djT',
        'USER': 'admin',
        'PASSWORD': 'Root110qwe',
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
# 自动显示  默认的 UTC  没有国际性
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
# 假设 你们没有配置
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')  后期

# 阿里云的 AK/SK
ACCESS_KEY_ID = "LTAIgnQgDlbvYcuZ"
ACCESS_KEY_SECRET = "b8WqmjNLMMOqDo2wsdJ82xSPCsbpE8"

# 签名 模板
SING_NAME = 'Python博文网'
TEMPLATE_CODE = 'SMS_161895371'

# 七牛
QI_NIU_ACCESS_KEY = 'cdFPS53dom8Raj4u6nI8QHmXpKsAHyhN15r1vBy1'
QI_NIU_SECRET_KEY = '-psPvDbRUtfQCaO2crmiJPfkcJWM_aDIDXHk55Lc'
QI_NIU_BUCKET_NAME = 'fubbs'

#  media
MEDIA_URL = '/media/'
# /home/pyvip/003/djT/media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 一页的新闻数量
ONE_PAGE_NEWS_COUNT = 2


# 百度云Userkey UserId
BAIDU_CLOUD_USER_ID = '2a2fd65e609b4d51bc067f1119fdbbce'
BAIDU_CLOUD_USER_KEY = '1164ca2f2d90479d'
